NumPy - Numerical Python

Advantages of NumPy Arrays:
1. Allows several Mathematical Operations.
2. Faster Operations

NumPy Arrays are more advance than list and tuples.

In [2]:
import numpy as np

List vs Numpy - Execution Time Taken

In [2]:
from time import process_time

Time Taken by a List to Execute.

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0014676100000006187


In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.001258092000000488


NumPy Arrays

In [5]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
#NumPy Array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
# creating a 1 dimensionl array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [13]:
c = np.array([(1,2,3,4), (5,6,7,8)], dtype=float)
print(c)
type(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


numpy.ndarray

Initial Placeholders in NumPy Arrays.

In [14]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)
type(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


numpy.ndarray

In [15]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# create an NumPy array of a particular value
z = np.full((5, 4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
# create a NumPy Array with Random values
b = np.random.random((3, 4))
print(b)

[[0.89360329 0.63796387 0.70822161 0.18273424]
 [0.30409937 0.57492611 0.96754841 0.6451615 ]
 [0.28808774 0.53168806 0.10556346 0.41979627]]


In [23]:
# Create a random integer values NumPy Arrays within a specific range
c = np.random.randint(10, 100, (3, 5))
print(c)

[[26 91 32 31 60]
 [56 78 87 53 75]
 [96 37 16 82 86]]


In [26]:
# create an NumPy array of evenly spaced values --> specifying the number of values required
d = np.linspace(10, 30, 6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [27]:
# array of evenly spaced values --> specifying the step
e = np.arange(10, 30, 5) # 5 = step-value
print(e)

[10 15 20 25]


In [29]:
# convert a list to a NumPy Array
list2 = [10, 20, 30, 40, 50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysis a NumPy Array

In [3]:
c = np.random.randint(10, 90, (5, 5))
print(c)

[[35 51 15 41 25]
 [64 41 83 89 63]
 [80 12 47 15 54]
 [60 46 55 49 49]
 [69 12 47 26 43]]


In [4]:
# array dimension
print(c.shape) # shape = rows and columns

(5, 5)


In [5]:
# number of dimension
print(c.ndim)

2


In [6]:
# Checking number of element in an NumPy Array
print(c.size)

25


In [7]:
# Checking the data type of values in a NumPy Array
print(c.dtype)

int64


Mathematical operations performed on NumPy Array

In [8]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [10]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))

In [11]:
print(a)
print(b)

[[2 9 9]
 [5 4 5]
 [8 1 7]]
[[13 17 18]
 [13 15 14]
 [12 12 11]]


In [12]:
print(a+b)

[[15 26 27]
 [18 19 19]
 [20 13 18]]


In [13]:
print(a-b)

[[-11  -8  -9]
 [ -8 -11  -9]
 [ -4 -11  -4]]


In [14]:
print(a*b)

[[ 26 153 162]
 [ 65  60  70]
 [ 96  12  77]]


In [15]:
print(a/b)

[[0.15384615 0.52941176 0.5       ]
 [0.38461538 0.26666667 0.35714286]
 [0.66666667 0.08333333 0.63636364]]


In [17]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))

In [18]:
print(np.add(a, b))

[[22 22 12]
 [11 14 23]
 [23 26 26]]


In [19]:
print(a)
print(b)

[[7 3 0]
 [1 2 5]
 [4 9 7]]
[[15 19 12]
 [10 12 18]
 [19 17 19]]


In [20]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[22 22 12]
 [11 14 23]
 [23 26 26]]
[[ -8 -16 -12]
 [ -9 -10 -13]
 [-15  -8 -12]]
[[105  57   0]
 [ 10  24  90]
 [ 76 153 133]]
[[0.46666667 0.15789474 0.        ]
 [0.1        0.16666667 0.27777778]
 [0.21052632 0.52941176 0.36842105]]


Array Manipulation

In [21]:
array = np.random.randint(0, 10, (2, 3))
print(array)
print(array.shape)

[[1 3 4]
 [0 6 4]]
(2, 3)


In [22]:
# create a transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 0]
 [3 6]
 [4 4]]
(3, 2)


In [23]:
array = np.random.randint(0, 10, (2, 3))
print(array)
print(array.shape)

[[3 3 7]
 [0 9 1]]
(2, 3)


In [24]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 0]
 [3 9]
 [7 1]]
(3, 2)


In [25]:
# Reshaping a NumPy Array
a = np.random.randint(0, 10, (2,3))
print(a)
print(a.shape)

[[0 9 0]
 [8 4 1]]
(2, 3)


In [26]:
b = a.reshape(3, 2)
print(b)
print(b.shape)

[[0 9]
 [0 8]
 [4 1]]
(3, 2)
